"""intent_leads: data_quality_score + quality_flags (Phase 6)

Revision ID: 72de0d2260ff
Revises: 7e743ef52c9d
Create Date: 2026-07-14 18:49:01.454685
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72de0d2260ff'
down_revision: str | None = '7e743ef52c9d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills the two columns on any existing rows (SQLite cannot
    # add a NOT NULL column to a populated table without one). New inserts use the
    # ORM-side defaults (0 / []).
    with op.batch_alter_table('intent_leads', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('data_quality_score', sa.Integer(), nullable=False, server_default=sa.text('0'))
        )
        batch_op.add_column(
            sa.Column('quality_flags', sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intent_leads', schema=None) as batch_op:
        batch_op.drop_column('quality_flags')
        batch_op.drop_column('data_quality_score')

    # ### end Alembic commands ###
