"""initial schema: leads, intent_leads, rejects, scrape_runs, checkpoints

Revision ID: 7e743ef52c9d
Revises: 
Create Date: 2026-07-14 13:53:31.871141
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e743ef52c9d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('query', sa.String(length=1024), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkpoints', schema=None) as batch_op:
        batch_op.create_index('uq_checkpoints_source_query', ['source', 'query'], unique=True)

    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_name', sa.String(length=512), nullable=False),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('linkedin_url', sa.String(length=1024), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('twitter', sa.String(length=255), nullable=True),
    sa.Column('company_size', sa.String(length=32), nullable=True),
    sa.Column('employee_count_est', sa.Integer(), nullable=True),
    sa.Column('founder', sa.String(length=255), nullable=True),
    sa.Column('ceo', sa.String(length=255), nullable=True),
    sa.Column('google_rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('business_hours', sa.String(length=512), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=False),
    sa.Column('lead_source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('data_quality_score', sa.Integer(), nullable=False),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ENRICHED', 'SCORED', 'EXPORTED', name='leadstatus', native_enum=False, length=16), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index('ix_leads_domain', ['domain'], unique=False)
        batch_op.create_index('ix_leads_source_url', ['source_url'], unique=False)
        batch_op.create_index('ix_leads_status', ['status'], unique=False)

    op.create_table('rejects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rejects', schema=None) as batch_op:
        batch_op.create_index('ix_rejects_source', ['source'], unique=False)

    op.create_table('scrape_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('query', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pages_visited', sa.Integer(), nullable=False),
    sa.Column('leads_found', sa.Integer(), nullable=False),
    sa.Column('rejects', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.create_index('ix_scrape_runs_source', ['source'], unique=False)

    op.create_table('intent_leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_profile_url', sa.String(length=1024), nullable=True),
    sa.Column('author_headline', sa.String(length=512), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('need_text', sa.Text(), nullable=False),
    sa.Column('need_category', sa.String(length=64), nullable=False),
    sa.Column('post_url', sa.String(length=1024), nullable=False),
    sa.Column('post_text', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('freshness_score', sa.Integer(), nullable=False),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('suggested_angle', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'SCORED', 'EXPORTED', name='intentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_url')
    )
    with op.batch_alter_table('intent_leads', schema=None) as batch_op:
        batch_op.create_index('ix_intent_leads_need_category', ['need_category'], unique=False)
        batch_op.create_index('ix_intent_leads_platform', ['platform'], unique=False)
        batch_op.create_index('ix_intent_leads_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intent_leads', schema=None) as batch_op:
        batch_op.drop_index('ix_intent_leads_status')
        batch_op.drop_index('ix_intent_leads_platform')
        batch_op.drop_index('ix_intent_leads_need_category')

    op.drop_table('intent_leads')
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_scrape_runs_source')

    op.drop_table('scrape_runs')
    with op.batch_alter_table('rejects', schema=None) as batch_op:
        batch_op.drop_index('ix_rejects_source')

    op.drop_table('rejects')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('ix_leads_status')
        batch_op.drop_index('ix_leads_source_url')
        batch_op.drop_index('ix_leads_domain')

    op.drop_table('leads')
    with op.batch_alter_table('checkpoints', schema=None) as batch_op:
        batch_op.drop_index('uq_checkpoints_source_query')

    op.drop_table('checkpoints')
    # ### end Alembic commands ###
